//! Build script: generate the compiled-in campaign manifest (Phase 5).
//!
//! Reads `assets/levels/campaign/NN-slug.lvl` and emits
//! `OUT_DIR/campaign_manifest.rs` with one `include_str!` per level, so an
//! installed binary needs no data directory (ADR-0007). The manifest is
//! sorted by file name, which is the `NN-` run order.

use std::fmt::Write as _;
use std::fs;
use std::path::Path;

fn main() {
    let dir = Path::new("assets/levels/campaign");
    let mut names: Vec<String> = Vec::new();
    if let Ok(entries) = fs::read_dir(dir) {
        for entry in entries.flatten() {
            let path = entry.path();
            if path.extension().map(|e| e == "lvl").unwrap_or(false) {
                if let Some(stem) = path.file_stem().and_then(|s| s.to_str()) {
                    names.push(stem.to_string());
                }
            }
        }
    }
    names.sort();

    let out = std::env::var("OUT_DIR").expect("OUT_DIR from cargo");
    let dest = Path::new(&out).join("campaign_manifest.rs");
    let mut src = String::from(
        "// Generated by build.rs: (&str id, &str source) per campaign level.\n\
         pub const CAMPAIGN: &[(&str, &str)] = &[\n",
    );
    for name in &names {
        // Absolute include path: the generated file lives in OUT_DIR, so a
        // relative path would resolve against OUT_DIR, not the repo.
        let _ = writeln!(
            src,
            "    (\"{name}\", include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \
             \"/assets/levels/campaign/{name}.lvl\"))),"
        );
    }
    src.push_str("];\n");
    fs::write(&dest, src).expect("write campaign manifest");

    println!("cargo:rerun-if-changed=assets/levels/campaign");
    println!("cargo:rerun-if-changed=build.rs");
}
